select 
make_timestamp (
date_part('year',current_date - interval (date_part('day', __time)) DAY), 
date_part('month',current_date - interval (date_part('day', __time)) DAY), 
date_part('day',current_date - interval (date_part('day', __time)) DAY), 
cast(round(24*random()) as bigint),0,00.00) as __time, 
ad_position,
adomain,
advertiser_id,
advertiser_name,
app_or_site,
app_site_domain,
app_site_name,
auction_type,
bid_floor_bucket,
bid_price_bucket,
campaign_name,
creative_type,
device_os,
device_osv,
device_region,
device_type,
has_imp,
interstitial,
line_item_id,
line_item_name,
mraid,
placement_type,
platform_browser,
player_size,
privacy,
pub_name,
sdk,
video_activity,
video_max_duration_bucket,
video_min_duration_bucket,
vpaid,
bid_cnt,
bid_floor,
bid_price_usd,
click_cnt,
click_reg_cnt,
click_vid_comp_cnt,
has_bid_floor_cnt,
imp_cnt,
media_spend_usd,
video_activity_cnt,
video_complete_cnt,
video_first_quartile_cnt,
video_midpoint_cnt,
video_skip_cnt,
video_start_cnt,
video_third_quartile_cnt,
winning_bid_price_usd
from bids_data_raw